# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: (DEV) Build and deploy Node.js project to Azure Function App - bk-sd-win

on:
  push:
    branches:
      - features/app-setup
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    environment: DEV
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Create env file'
        shell: bash
        env:
          SUPER_SECRET: ${{ secrets.DEV }}
        run: |
          echo "$SUPER_SECRET"
          touch .env
          echo ${{secrets}}
          echo ${{ secrets.DEV }} | base64 --decode > echo  .env
          echo "======== env file created ========"
          cat .env

      - name: 'Resolve Project Dependencies Using Npm'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm ci
          npm run build --if-present
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'bk-sd-win'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C06C04CE544146F685FD5635DE35CA46 }}
